test:
  locustfile: locustfiles/api_user.py
  shape: shapes/spike_shape.py

env:
  SPIKE_PRE_USERS: 10
  SPIKE_PRE_SPAWN: 2
  SPIKE_PRE_DURATION: 10

  SPIKE_PEAK_USERS: 200
  SPIKE_PEAK_SPAWN: 50
  SPIKE_PEAK_DURATION: 20

  SPIKE_POST_USERS: 10
  SPIKE_POST_SPAWN: 10
  SPIKE_POST_DURATION: 30